# $Id$

include ../../../../config.mk

TPLFILES = *.tpl
TPLDIR = $(ETCDIR)/templates/format_templates
all:
	@echo "Done."

test:
	@echo "Not implemented."

install:
	$(INSTALL) -m 664 $(TPLFILES) $(TPLDIR)
