# $Id$

include ../../../../config.mk

TPLFILES = *.tpl
TPLDIR = $(ETCLOCALDIR)/templates/format_templates/
all:
	@echo "Done."

test:
	@echo "Not implemented."

install:
	mkdir -p $(TPLDIR)
	$(INSTALL) -m 664 $(TPLFILES) $(TPLDIR)


