# $Id$

include ../../config.mk

CSSFILES = bootstrap.css blogforever.css \
		font-awesome.css font-awesome-ie7.css \
		fontawesome-webfont.eot fontawesome-webfont.svg \
		fontawesome-webfont.ttf fontawesome-webfont.woff
CSSDIR = $(PREFIX)/var/www/css/

all:
	@echo "Done."

test:
	@echo "Not implemented."

install:
	$(INSTALL) $(CSSFILES) $(CSSDIR)
