# $Id$

include ../../config.mk

CSSFILES = bootstrap.css blogforever.css \
		font-awesome.css font-awesome-ie7.min.css \
		font-awesome.min.css
CSSDIR = $(PREFIX)/var/www/css/

all:
	@echo "Done."

test:
	@echo "Not implemented."

install:
	$(INSTALL) $(CSSFILES) $(CSSDIR)
